dialect = "us"
timezone = "local"
auto_sync = true
update_check = false
sync_address = "https://api.atuin.sh"
sync_frequency = "10m"
search_mode = "fuzzy"
style = "full"
show_help = false
enter_accept = true

[sync]
records = true

[theme]
name = "catppuccin-mocha-lavender"

[ui]
columns = ["duration", "command"]
