export alias su = scoop update
export alias si = scoop install
export alias sui = scoop uninstall
export alias sse = scoop search
export alias sst = scoop status
export alias sl = scoop list
export alias sbl = scoop bucket list
export alias sba = scoop bucket add
export alias sbr = scoop bucket rm
export alias sui = scoop uninstall
