showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - text
    - traffic
hideTrayIcon: false
connShowProcess: true
theme: 1
trayColorTransparent: true
showTrayProxyDelayIndicator: true
checkForUpdates: false
editor: 1
specifyHttpProxyProtocol: false
fontFamily: Maple Mono NF CN
useSystemEmoji: true
useModeIcons: false
trayColorForeground: "#1d1c2e"
