#!/bin/bash

source "$CONFIG_DIR/colors.sh"   # Loads all defined colors
source "$CONFIG_DIR/icons.sh"    # Loads all defined icons
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

export FONT="Hack Nerd Font"

PADDINGS=3

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

bar=(
  height=35
  color=$BAR_COLOR
  border_width=3
  border_color=$SURFACE0
  corner_radius=10
  blur_radius=15
  shadow=on
  position=top
  sticky=on
  padding_right=5
  padding_left=5
  y_offset=1
  margin=5
  topmost=window
  display=all
  notch_width=200
)

sketchybar --bar "${bar[@]}"

default=(
  updates=when_shown
  padding_left=5
  padding_right=5
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$Font:Bold:13.0"
  label.color=0xffffffff
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  label.shadow.drawing=on
  label.shadow.distance=2
  label.shadow.color=0xff000000
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${default[@]}"

# Left
source "$PLUGIN_DIR/logo/item.sh"
source "$PLUGIN_DIR/spaces/item.sh"

# Right
source "$PLUGIN_DIR/date/item.sh"
source "$PLUGIN_DIR/battery/item.sh"
source "$PLUGIN_DIR/volume/item.sh"
source "$PLUGIN_DIR/chat/wechat.sh"
source "$PLUGIN_DIR/chat/qq.sh"
source "$PLUGIN_DIR/brew/item.sh"
source "$PLUGIN_DIR/stats/item.sh"

brackets=(
  background.color=$BACKGROUND_1
  background.corner_radius=8
  background.height=28
  background.border_color=$OVERLAY0
  icon.highlight_color=$LAVENDER
  icon.padding_left=10
  icon.padding_right=10
  padding_left=2
  padding_right=2
  background.drawing=on
)

sketchybar --add bracket apps qq wechat volume battery brew \
  --set apps "${brackets[@]}"

sketchybar --hotload false
sketchybar --update
