#!/bin/bash

subtext1=0xffbac2de
subtext0=0xffa6adc8
overlay2=0xff9399b2
overlay1=0xff7f849c
overlay0=0xff6c7086
surface2=0xff585b70
surface1=0xff45475a
surface0=0xff313244
lavendar=0xbbb4befe

options=(
  style=round
  width=3.0
  hidpi=off
  active_color=$lavendar
  inactive_color=$surface0
)

borders "${options[@]}"
