[metadata]
name = "dirs"
description = "A channel to select from directories"
requirements = ["fd", "eza"]

[source]
command = ["fd -t d", "fd -t d --hidden"]

[preview]
command = "eza -la --git --icons=always --color=always '{}'"

[keybindings]
shortcut = "f2"
