[metadata]
name = "dirs"
description = "A channel to select from directories"
requirements = ["fd"]

[source]
command = ["fd -t d", "fd -t d --hidden"]

[preview]
command = "lla --sizemap '{}'"

[keybindings]
shortcut = "f2"
