
[metadata]
name = "nu-commands"
description = "A channel to select from your nu history"

[source]
# command = "nu --config ~/.config/nushell/config.nu -c 'help commands | where command_type == alias | select name description | to csv'"
command = "nu --config ~/.config/nushell/config.nu -c 'help commands | select name description | to csv'"
display = "{split:,:0}"
output = "{split:,:0}"

[preview]
command = "nu --config ~/.config/nushell/config.nu -c 'help {split:,:0}'"
