[metadata]
name = "procs"
description = "A channel to find and manage running processes"
requirements = ["ps"]

[source]
command = "ps -e -o pid=,ucomm= | awk '{print $1, $2}'"
display = "{split: :1}"
output = "{split: :0}"

[preview]
command = "ps -p '{split: :0}' -o user,pid,ppid,state,%cpu,%mem"

[actions.kill]
description = "Kill the selected process(es)"
command = "kill -9 {split: :0}"
mode = "execute"

[keybindings]
ctrl-k = "actions:kill"
