[flavor]
use = "catppuccin-mocha"
dark = "catppuccin-mocha"

[icon]

rules = [
	# Programming
	{ name = "*.c", text = "", fg = "#89b4fa" },
	{ name = "*.cpp", text = "", fg = "#89b4fa" },
	{ name = "*.class", text = "", fg = "#fab387" },
	{ name = "*.cs", text = "󰌛", fg = "#a6e3a1" },
	{ name = "*.css", text = "", fg = "#f5c2e7" },
	{ name = "*.elm", text = "", fg = "#74c7ec" },
	{ name = "*.fish", text = "", fg = "#a6e3a1" },
	{ name = "*.go", text = "", fg = "#89dceb" },
	{ name = "*.h", text = "", fg = "#89b4fa" },
	{ name = "*.hpp", text = "", fg = "#89b4fa" },
	{ name = "*.html", text = "", fg = "#fab387" },
	{ name = "*.jar", text = "", fg = "#fab387" },
	{ name = "*.java", text = "", fg = "#fab387" },
	{ name = "*.js", text = "", fg = "#f9e2af" },
	{ name = "*.jsx", text = "", fg = "#89dceb" },
	{ name = "*.lua", text = "", fg = "#cba6f7" },
	{ name = "*.nix", text = "", fg = "#89b4fa" },
	{ name = "*.nu", text = ">", fg = "#94e2d5" },
	{ name = "*.php", text = "", fg = "#cba6f7" },
	{ name = "*.py", text = "", fg = "#f9e2af" },
	{ name = "*.rb", text = "", fg = "#f38ba8" },
	{ name = "*.rs", text = "", fg = "#fab387" },
	{ name = "*.sbt", text = "", fg = "#f38ba8" },
	{ name = "*.scala", text = "", fg = "#f38ba8" },
	{ name = "*.scss", text = "", fg = "#f5c2e7" },
	{ name = "*.sh", text = "", fg = "#a6e3a1" },
	{ name = "*.swift", text = "", fg = "#fab387" },
	{ name = "*.ts", text = "", fg = "#89b4fa" },
	{ name = "*.tsx", text = "", fg = "#89dceb" },
	{ name = "*.vim", text = "", fg = "#a6e3a1" },
	{ name = "*.vue", text = "󰡄", fg = "#a6e3a1" },

	# Text
	{ name = "*.conf", text = "", fg = "#a6adc8" },
	{ name = "*.ini", text = "", fg = "#a6adc8" },
	{ name = "*.json", text = "", fg = "#f9e2af" },
	{ name = "*.kdl", text = "", fg = "#a6adc8" },
	{ name = "*.md", text = "", fg = "#cdd6f4" },
	{ name = "*.toml", text = "", fg = "#a6adc8" },
	{ name = "*.txt", text = "", fg = "#a6adc8" },
	{ name = "*.yaml", text = "", fg = "#a6adc8" },
	{ name = "*.yml", text = "", fg = "#a6adc8" },

	# Archives
	{ name = "*.7z", text = "", fg = "#f2cdcd" },
	{ name = "*.bz2", text = "", fg = "#f2cdcd" },
	{ name = "*.gz", text = "", fg = "#f2cdcd" },
	{ name = "*.rar", text = "", fg = "#f2cdcd" },
	{ name = "*.tar", text = "", fg = "#f2cdcd" },
	{ name = "*.xz", text = "", fg = "#f2cdcd" },
	{ name = "*.zip", text = "", fg = "#f2cdcd" },

	# Images
	{ name = "*.HEIC", text = "", fg = "#cba6f7" },
	{ name = "*.avif", text = "", fg = "#cba6f7" },
	{ name = "*.bmp", text = "", fg = "#cba6f7" },
	{ name = "*.gif", text = "", fg = "#cba6f7" },
	{ name = "*.ico", text = "", fg = "#f9e2af" },
	{ name = "*.jpeg", text = "", fg = "#cba6f7" },
	{ name = "*.jpg", text = "", fg = "#cba6f7" },
	{ name = "*.png", text = "", fg = "#cba6f7" },
	{ name = "*.svg", text = "", fg = "#fab387" },
	{ name = "*.webp", text = "", fg = "#cba6f7" },

	# Movies
	{ name = "*.avi", text = "", fg = "#fab387" },
	{ name = "*.mkv", text = "", fg = "#fab387" },
	{ name = "*.mov", text = "", fg = "#fab387" },
	{ name = "*.mp4", text = "", fg = "#fab387" },
	{ name = "*.webm", text = "", fg = "#fab387" },

	# Audio
	{ name = "*.aac", text = "", fg = "#89dceb" },
	{ name = "*.flac", text = "", fg = "#89dceb" },
	{ name = "*.m4a", text = "", fg = "#89dceb" },
	{ name = "*.mp3", text = "", fg = "#89dceb" },
	{ name = "*.ogg", text = "", fg = "#89dceb" },
	{ name = "*.wav", text = "", fg = "#89dceb" },

	# Documents
	{ name = "*.csv", text = "", fg = "#a6e3a1" },
	{ name = "*.doc", text = "", fg = "#89b4fa" },
	{ name = "*.doct", text = "", fg = "#89b4fa" },
	{ name = "*.docx", text = "", fg = "#89b4fa" },
	{ name = "*.dot", text = "", fg = "#89b4fa" },
	{ name = "*.ods", text = "", fg = "#a6e3a1" },
	{ name = "*.ots", text = "", fg = "#a6e3a1" },
	{ name = "*.pdf", text = "", fg = "#f38ba8" },
	{ name = "*.pom", text = "", fg = "#fab387" },
	{ name = "*.pot", text = "", fg = "#fab387" },
	{ name = "*.potx", text = "", fg = "#fab387" },
	{ name = "*.ppm", text = "", fg = "#fab387" },
	{ name = "*.ppmx", text = "", fg = "#fab387" },
	{ name = "*.pps", text = "", fg = "#fab387" },
	{ name = "*.ppsx", text = "", fg = "#fab387" },
	{ name = "*.ppt", text = "", fg = "#fab387" },
	{ name = "*.pptx", text = "", fg = "#fab387" },
	{ name = "*.xlc", text = "", fg = "#a6e3a1" },
	{ name = "*.xlm", text = "", fg = "#a6e3a1" },
	{ name = "*.xls", text = "", fg = "#a6e3a1" },
	{ name = "*.xlsm", text = "", fg = "#a6e3a1" },
	{ name = "*.xlsx", text = "", fg = "#a6e3a1" },
	{ name = "*.xlt", text = "", fg = "#a6e3a1" },

	# Lockfiles
	{ name = "*.lock", text = "", fg = "#6c7086" },

	# Misc
	{ name = "*.bin", text = "", fg = "#f38ba8" },
	{ name = "*.exe", text = "", fg = "#f38ba8" },
	{ name = "*.pkg", text = "", fg = "#f38ba8" },

	# Dotfiles
	{ name = ".DS_Store", text = "", fg = "#585b70" },
	{ name = ".bashprofile", text = "", fg = "#a6e3a1" },
	{ name = ".bashrc", text = "", fg = "#a6e3a1" },
	{ name = ".gitattributes", text = "", fg = "#585b70" },
	{ name = ".gitignore", text = "", fg = "#585b70" },
	{ name = ".gitmodules", text = "", fg = "#585b70" },
	{ name = ".vimrc", text = "", fg = "#a6e3a1" },
	{ name = ".zprofile", text = "", fg = "#a6e3a1" },
	{ name = ".zshenv", text = "", fg = "#a6e3a1" },
	{ name = ".zshrc", text = "", fg = "#a6e3a1" },

	# Named files
	{ name = "COPYING", text = "󰿃", fg = "#f9e2af" },
	{ name = "Containerfile", text = "󰡨", fg = "#89b4fa" },
	{ name = "Dockerfile", text = "󰡨", fg = "#89b4fa" },
	{ name = "LICENSE", text = "󰿃", fg = "#f9e2af" },

	# Directories
	{ name = ".config/", text = "" },
	{ name = ".git/", text = "" },
	{ name = "Desktop/", text = "" },
	{ name = "Development/", text = "" },
	{ name = "Documents/", text = "" },
	{ name = "Downloads/", text = "" },
	{ name = "Library/", text = "" },
	{ name = "Movies/", text = "" },
	{ name = "Music/", text = "" },
	{ name = "Pictures/", text = "" },
	{ name = "Public/", text = "" },
	{ name = "Videos/", text = "" },

	# Default
	{ name = "*", text = "" },
	{ name = "*/", text = "" },
]
