# ====================================================
# *                       Colors                     *
# ====================================================
rosewater: &rosewater "#f5e0dc"
flamingo: &flamingo "#f2cdcd"
pink: &pink "#f5c2e7"
mauve: &mauve "#cba6f7"
teal: &teal "#94e2d5"
sky: &sky "#89dceb"
sapphire: &sapphire "#74c7ec"
blue: &blue "#82aaff"
text: &text "#cdd6f4"
surface0: &surface0 "#313244"
base: &base "#1e1e2e"
mantle: &mantle "#181825"
crust: &crust "#11111b"
# TAG top bar right component
lavender: &lavender "#b4befe"
light-turquoise: &turquoise "#b4cfff"
light-blue: &light-blue "#"
tokyo-night-blue: &tokyo-night-blue "#82aaff"
olive-green: &olive-green "#c3d08d"
red: &red "#f38ba8"
# ====================================================
# *                     Separator                    *
# ====================================================
Separator_color: &seperator_color "#98a4f22e"
Separator_size: &seperator_size "25px"
Separator: &seperator "|"

bar:
  height: "27px"
  position: "top"
  opacity: 0.99
  background: *crust
  foreground: *mauve
  font_family: "Maple Mono NF CN"
  font_size: "12px"
  padding: "4px 8px"
  offset_x: 0
  offset_y: 0
  border_radius: 10
  border_color: "#343A41"
  border_width: "1"

  components_left:
    - type: "text"
      text: "󰣇 "
      foreground: *teal
    - type: "text"
      text: "Efterklang "
      font_family: "Monaspace Radon Var"
      foreground: *teal
      # left_click_command: "exec "
    - type: "workspaces"
      default_workspace_foreground: *mauve
      focused_workspace_foreground: *teal
      default_workspace_background: "transparent"
      focused_workspace_background: "transparent"
      displayed_workspace_background: "transparent"
  components_center:
    # - type: "window title"
    - type: "clock"
      time_formatting: " H:mm:ss "
      foreground: *mauve
    - type: "clock"
      time_formatting: "ddd"
      foreground: "#eed49f"
  components_right:
    - type: "tiling direction"
      foreground: *lavender
      label_horizontal: "<attr fs='15'>󰯌 </attr>" #⮂ 󰚉 ⬓ 󰯌
      label_vertical: "<attr fs='15'>󰯋 </attr>" #⮁ 󰚈 󱂪 󰯋
    - type: "binding mode"
      foreground: *red
      margin: "0px 10px 0px 0px"
    - type: "music"
      foreground: *lavender
      label_not_playing: "<attr fs='15'> </attr>Music"
      label_paused: "<attr fs='15'>󰝛 </attr>{song_title}"
      label_playing: "<attr fs='15'>󰥠 </attr>{song_title}"
      max_title_length: 30
    - type: "text"
      text: *seperator
      font_size: *seperator_size
      foreground: *seperator_color
    - type: "weather"
      # chengdu: 30.3936N 104.0348E
      latitude: 30.3936
      longitude: 104.0348
      foreground: *turquoise
      label: "{temperature_celsius}°C"
      label_sun: "<attr fs='14'>☀️</attr>{temperature_celsius}°C"
      label_moon: "<attr fs='14'>🌙</attr>{temperature_celsius}°C"
      label_cloud_moon: "<attr fs='14'>🌙 </attr>{temperature_celsius}°C"
      label_cloud_sun: "<attr fs='14'>⛅</attr>{temperature_celsius}°C"
      label_cloud_moon_rain: "<attr fs='14'>🌙 </attr>{temperature_celsius}°C"
      label_cloud_sun_rain: "<attr fs='14'>🌦️</attr>{temperature_celsius}°C"
      label_cloud_rain: "<attr fs='14'>🌧️</attr>{temperature_celsius}°C"
      label_snow_flake: "<attr fs='14'>❄️</attr>{temperature_celsius}°C"
      label_thunderstorm: "<attr fs='14'>⚡</attr>{temperature_celsius}°C"
      label_cloud: "<attr fs='14'>☁️</attr>{temperature_celsius}°C"
    - type: "text"
      text: *seperator
      font_size: *seperator_size
      foreground: *seperator_color
    - type: "cpu"
      foreground: *tokyo-night-blue
      label: "<attr fs='15'> </attr>{percent_usage}󱉸"
      margin: "0px 8px 0px 0px"
      refresh_interval_ms: 1000
    - type: "gpu"
      foreground: *tokyo-night-blue
      label: "<attr fs='15'>󰍛 </attr>{percent_usage}󱉸"
      margin: "0px 8px 0px 0px"
      refresh_interval_ms: 1000
    - type: "memory"
      foreground: *tokyo-night-blue
      label: "<attr fs='13'>  </attr>{percent_usage}󱉸"
      refresh_interval_ms: 1000
    - type: "text"
      text: *seperator
      font_size: *seperator_size
      foreground: *seperator_color
    - type: "volume"
      label_low: "<attr fs='15'>🔊</attr>{volume_level}"
      label_medium: "<attr fs='15'>🔊</attr>{volume_level}"
      label_high: "<attr fs='15'>🔊</attr>{volume_level}"
      label_mute: "<attr fs='15'>🔕</attr>{volume_level}"
      foreground: *olive-green
      margin: "0px 0px 0px 0px"
    - type: text
      text: "% "
      foreground: *olive-green
      left_click_command: "exec 'C:/Users/24138/.glaze-wm/scripts/toggleMute.exe'"
    - type: "battery"
      # background: *surface0
      foreground: *olive-green
      label_draining: "<attr fs='15'>󰂂 </attr>{battery_level}%"
      label_power_saver: "<attr fs='15'>󰌪 </attr>{battery_level}%"
      label_charging: "<attr fs='15'>󰂅 </attr>{battery_level}%"
    - type: "text"
      text: *seperator
      font_size: *seperator_size
      foreground: *seperator_color
    - type: "clock"
      time_formatting: " yyyy-M-d "
      foreground: *red
    - type: "text"
      text: "  "
      left_click_command: "exec taskmgr"
      foreground: *red
      font_size: "14px"
      margin: "0px 10px 0px 0px"
      # left_click_command: "exec '%userprofile%/.glaze-wm/scripts/shutdown.bat'"
      right_click_command: ""

general:
  focus_follows_cursor: true
  cursor_follows_focus: false
  toggle_workspace_on_refocus: true
  show_floating_on_top: false
  floating_window_move_amount: "5%"
  center_new_floating_windows: true
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  inner_gap: "2"
  outer_gap: "1"

# Highlight active/inactive windows with a colored border.
focus_borders:
  active:
    enabled: true
    color: "#8aadf4"

  inactive:
    enabled: true
    color: "#8087a2"

workspaces:
  - name: "1"
    display_name: " "
    keep_alive: true
  - name: "2"
    display_name: " "
  - name: "3"
    display_name: "󰨞 "
  - name: "4"
    display_name: "󰨊 "
  - name: "5"
    display_name: "󰇩 "
  - name: "6"
    display_name: " "

window_rules:
  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  - command: "ignore"
    match_process_name: "/Flow.Launcher|ScreenClippingHost/"

  - command: "set floating"
    match_process_name: "/Taskmgr|ScreenClippingHost|Clash for Windows/"

  - command: "ignore"
    match_title: "/.*[Pp]hoto.*|图片查看器|explorer|SnippingTool|.*[Cc]amera.*|.*QQ.*|.*聊天记录.*|WeChat|Feishu/"

  - command: "move to workspace 2"
    match_process_name: "/WeChat|Feishu/"

  - commands: ["move to workspace 4"]
    match_process_name: "wezterm-gui"

  - commands: ["move to workspace 6", resize borders 0px -7px -7px -7px]
    match_process_name: "/[sS]team/"

binding_modes:
  - name: "view"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      # Move focused window in a given direction.
      - command: "move left"
        binding: "Alt+A"
      - command: "move right"
        binding: "Alt+D"
      - command: "move up"
        binding: "Alt+W"
      - command: "move down"
        binding: "Alt+D"
      - command: "tiling direction toggle"
        binding: "Alt+V"
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]
  - name: "lock"
    keybindings:
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  - command: "binding mode view"
    binding: "Alt+C"
  - command: "binding mode lock"
    binding: "Alt+Z"
  - command: "toggle floating"
    binding: "Alt+Space"
  - command: "tiling direction toggle"
    binding: "Alt+V"
  - command: "reload config"
    binding: "Alt+Shift+C"
  - command: "set minimized"
    binding: "Alt+M"
  - commands: ["exec D:/Application/WezTerm/wezterm-gui.exe"]
    binding: "Ctrl+Enter"
  # Change focus tab
  - command: "focus left"
    binding: "Alt+H"
  - command: "focus right"
    binding: "Alt+L"
  - command: "focus up"
    binding: "Alt+K"
  - command: "focus down"
    binding: "Alt+J"
  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace next"
    binding: "Alt+0"
  - command: "focus workspace prev"
    binding: "Alt+9"

    # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+Shift+H"
  - command: "focus workspace prev"
    binding: "Alt+Shift+L"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", focus workspace 1]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", focus workspace 2]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", focus workspace 3]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", focus workspace 4]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", focus workspace 5]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", focus workspace 6]
    binding: "Alt+Shift+6"
